### ISSUE TITLE
【確認待ち】PHP8.2でHTMLサイトマップ表示エラー

### ISSUE THREAD

**Issue by urihcim** [vektor-inc/vk-all-in-one-expansion-unit#946]
PHP8.2でHTMLサイトマップが表示できなくなっているようです。PHP8.1はOKでした。

PHP バージョン: 8.2.4
VK All in One Expansion Unit バージョン: 9.88.0.0

```
PHP Fatal error:  Uncaught ValueError: mb_convert_kana(): Argument #2 ($mode) contains invalid flag: 'v' in /var/www/wordpress/wp-content/plugins/vk-all-in-one-expansion-unit/inc/sitemap-page/sitemap-page.php:124
Stack trace:
#0 /var/www/wordpress/wp-content/plugins/vk-all-in-one-expansion-unit/inc/sitemap-page/sitemap-page.php(124): mb_convert_kana()
#1 /var/www/wordpress/wp-includes/shortcodes.php(355): vkExUnit_sitemap()
#2 [internal function]: do_shortcode_tag()
#3 /var/www/wordpress/wp-includes/shortcodes.php(227): preg_replace_callback()
#4 /var/www/wordpress/wp-content/plugins/vk-all-in-one-expansion-unit/inc/sitemap-page/sitemap-page.php(88): do_shortcode()
#5 /var/www/wordpress/wp-includes/class-wp-hook.php(308): veu_show_sitemap()
#6 /var/www/wordpress/wp-includes/plugin.php(205): WP_Hook->apply_filters()
#7 /var/www/wordpress/wp-includes/post-template.php(255): apply_filters()
#8 /var/www/wordpress/wp-content/themes/lightning/_g3/template-parts/entry.php(45): the_content()
#9 /var/www/wordpress/wp-includes/template.php(785): require('...')
#10 /var/www/wordpress/wp-content/themes/lightning/functions.php(148): load_template()
#11 /var/www/wordpress/wp-content/themes/lightning/_g3/template-parts/main-singular.php(19): lightning_get_template_part()
#12 /var/www/wordpress/wp-includes/template.php(785): require('...')
#13 /var/www/wordpress/wp-content/themes/lightning/functions.php(148): load_template()
#14 /var/www/wordpress/wp-content/themes/lightning/_g3/index.php(73): lightning_get_template_part()
#15 /var/www/wordpress/wp-includes/template.php(785): require('...')
#16 /var/www/wordpress/wp-content/themes/lightning/functions.php(148): load_template()
#17 /var/www/wordpress/wp-content/themes/lightning/index.php(7): lightning_get_template_part()
#18 /var/www/wordpress/wp-includes/template-loader.php(106): include('...')
#19 /var/www/wordpress/wp-blog-header.php(19): require_once('...')
#20 /var/www/wordpress/index.php(17): require('...')
#21 {main}
  thrown in /var/www/wordpress/wp-content/plugins/vk-all-in-one-expansion-unit/inc/sitemap-page/sitemap-page.php on line 124
```

**Comment by kurudrive** [comment]
@urihcim ご報告ありがとうございます。

**Comment by drill-lancer** [comment]
@kurudrive 
https://github.com/vektor-inc/vk-all-in-one-expansion-unit/blob/8d479b9b9b1702a5ace7ecc7afdcf3e96e7e5477/inc/sitemap-page/sitemap-page.php#L116-L125

多分 kvrn の大文字・小文字が問題となっていそうなのですが、この  mb_convert_kana() では一体何をしようとしているのか分かりますか？
https://www.php.net/manual/ja/function.mb-convert-kana.php

**Comment by kurudrive** [comment]
9.88.1.0 より後のバージョンで修正済です。
お急ぎの場合は 
https://github.com/vektor-inc/vk-all-in-one-expansion-unit/pull/948/files
を修正ください。

よろしくお願いいたします。
